name: deploy to remote

on:
  push:
    branches:
      # 起動タイミングはリリースブランチへのプッシュ
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # check out
    - uses: actions/checkout@v1

    - name: ssh key generate
      run: echo "$SSH_PRIVATE_KEY" > key && chmod 600 key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: install and build
      run: |
        npm ci
        npm run build-prod-github-actions
      env:
        REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

    - name: rsync deploy
      run: rsync -auzrv -e "ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p $PORT" --delete ./build/ $USERNAME@$SERVER:/home/$USERNAME/$USERNAME.xsrv.jp/public_html/ --exclude .htaccess
      env:
        SERVER: ${{ secrets.SERVER }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
